#ifndef MM_ADDRESS_H
#define MM_ADDRESS_H

#define ENTRY_DIR_PAGES       0

#define TOTAL_PAGES 1024
#define NUM_PAG_KERNEL 256
#define PAG_LOG_INIT_CODE (L_USER_START>>12)
#define FRAME_INIT_CODE (PH_USER_START>>12)
#define NUM_PAG_CODE 8
#define PAG_LOG_INIT_DATA (PAG_LOG_INIT_CODE+NUM_PAG_CODE)
#define NUM_PAG_DATA 20
#define NUM_PAG_TH_STACKS 8
#define PAG_LOG_TH_START (PAG_LOG_INIT_CODE+NUM_PAG_CODE+NUM_PAG_DATA)
#define PAG_LOG_INIT_CPY (PAG_LOG_INIT_CODE+NUM_PAG_CODE+NUM_PAG_DATA+NUM_PAG_TH_STACKS)
#define PAG_LOG_INIT_HEAP (PAG_LOG_INIT_CPY + 1)
#define NUM_PAG_HEAP (TOTAL_PAGES-NUM_PAG_KERNEL-NUM_PAG_CODE-NUM_PAG_DATA-NUM_PAG_TH_STACKS-1)
#define PAGE_SIZE 0x1000

/* Memory distribution */
/***********************/


#define KERNEL_START        0x10000
#define L_USER_START        0x100000
#define PH_USER_START       0x100000
#define USER_ESP	L_USER_START+(NUM_PAG_CODE+NUM_PAG_DATA)*0x1000-16


#define USER_FIRST_PAGE	(L_USER_START>>12)
#define THREAD_WRAPPER_DIR 0x107500

#define PH_PAGE(x) (x>>12)

#endif

